// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/login-gateway/pkg/db/ent/loginhistory"
	"github.com/NpoolPlatform/login-gateway/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// LoginHistoryQuery is the builder for querying LoginHistory entities.
type LoginHistoryQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.LoginHistory
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LoginHistoryQuery builder.
func (lhq *LoginHistoryQuery) Where(ps ...predicate.LoginHistory) *LoginHistoryQuery {
	lhq.predicates = append(lhq.predicates, ps...)
	return lhq
}

// Limit adds a limit step to the query.
func (lhq *LoginHistoryQuery) Limit(limit int) *LoginHistoryQuery {
	lhq.limit = &limit
	return lhq
}

// Offset adds an offset step to the query.
func (lhq *LoginHistoryQuery) Offset(offset int) *LoginHistoryQuery {
	lhq.offset = &offset
	return lhq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lhq *LoginHistoryQuery) Unique(unique bool) *LoginHistoryQuery {
	lhq.unique = &unique
	return lhq
}

// Order adds an order step to the query.
func (lhq *LoginHistoryQuery) Order(o ...OrderFunc) *LoginHistoryQuery {
	lhq.order = append(lhq.order, o...)
	return lhq
}

// First returns the first LoginHistory entity from the query.
// Returns a *NotFoundError when no LoginHistory was found.
func (lhq *LoginHistoryQuery) First(ctx context.Context) (*LoginHistory, error) {
	nodes, err := lhq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{loginhistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lhq *LoginHistoryQuery) FirstX(ctx context.Context) *LoginHistory {
	node, err := lhq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LoginHistory ID from the query.
// Returns a *NotFoundError when no LoginHistory ID was found.
func (lhq *LoginHistoryQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = lhq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{loginhistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lhq *LoginHistoryQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := lhq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LoginHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one LoginHistory entity is not found.
// Returns a *NotFoundError when no LoginHistory entities are found.
func (lhq *LoginHistoryQuery) Only(ctx context.Context) (*LoginHistory, error) {
	nodes, err := lhq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{loginhistory.Label}
	default:
		return nil, &NotSingularError{loginhistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lhq *LoginHistoryQuery) OnlyX(ctx context.Context) *LoginHistory {
	node, err := lhq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LoginHistory ID in the query.
// Returns a *NotSingularError when exactly one LoginHistory ID is not found.
// Returns a *NotFoundError when no entities are found.
func (lhq *LoginHistoryQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = lhq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{loginhistory.Label}
	default:
		err = &NotSingularError{loginhistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lhq *LoginHistoryQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := lhq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LoginHistories.
func (lhq *LoginHistoryQuery) All(ctx context.Context) ([]*LoginHistory, error) {
	if err := lhq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return lhq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (lhq *LoginHistoryQuery) AllX(ctx context.Context) []*LoginHistory {
	nodes, err := lhq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LoginHistory IDs.
func (lhq *LoginHistoryQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := lhq.Select(loginhistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lhq *LoginHistoryQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := lhq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lhq *LoginHistoryQuery) Count(ctx context.Context) (int, error) {
	if err := lhq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return lhq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (lhq *LoginHistoryQuery) CountX(ctx context.Context) int {
	count, err := lhq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lhq *LoginHistoryQuery) Exist(ctx context.Context) (bool, error) {
	if err := lhq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return lhq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (lhq *LoginHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := lhq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LoginHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lhq *LoginHistoryQuery) Clone() *LoginHistoryQuery {
	if lhq == nil {
		return nil
	}
	return &LoginHistoryQuery{
		config:     lhq.config,
		limit:      lhq.limit,
		offset:     lhq.offset,
		order:      append([]OrderFunc{}, lhq.order...),
		predicates: append([]predicate.LoginHistory{}, lhq.predicates...),
		// clone intermediate query.
		sql:  lhq.sql.Clone(),
		path: lhq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LoginHistory.Query().
//		GroupBy(loginhistory.FieldAppID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (lhq *LoginHistoryQuery) GroupBy(field string, fields ...string) *LoginHistoryGroupBy {
	group := &LoginHistoryGroupBy{config: lhq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := lhq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return lhq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AppID uuid.UUID `json:"app_id,omitempty"`
//	}
//
//	client.LoginHistory.Query().
//		Select(loginhistory.FieldAppID).
//		Scan(ctx, &v)
//
func (lhq *LoginHistoryQuery) Select(fields ...string) *LoginHistorySelect {
	lhq.fields = append(lhq.fields, fields...)
	return &LoginHistorySelect{LoginHistoryQuery: lhq}
}

func (lhq *LoginHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, f := range lhq.fields {
		if !loginhistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lhq.path != nil {
		prev, err := lhq.path(ctx)
		if err != nil {
			return err
		}
		lhq.sql = prev
	}
	return nil
}

func (lhq *LoginHistoryQuery) sqlAll(ctx context.Context) ([]*LoginHistory, error) {
	var (
		nodes = []*LoginHistory{}
		_spec = lhq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &LoginHistory{config: lhq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, lhq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (lhq *LoginHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lhq.querySpec()
	_spec.Node.Columns = lhq.fields
	if len(lhq.fields) > 0 {
		_spec.Unique = lhq.unique != nil && *lhq.unique
	}
	return sqlgraph.CountNodes(ctx, lhq.driver, _spec)
}

func (lhq *LoginHistoryQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := lhq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (lhq *LoginHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   loginhistory.Table,
			Columns: loginhistory.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: loginhistory.FieldID,
			},
		},
		From:   lhq.sql,
		Unique: true,
	}
	if unique := lhq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := lhq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loginhistory.FieldID)
		for i := range fields {
			if fields[i] != loginhistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lhq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lhq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lhq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lhq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lhq *LoginHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lhq.driver.Dialect())
	t1 := builder.Table(loginhistory.Table)
	columns := lhq.fields
	if len(columns) == 0 {
		columns = loginhistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lhq.sql != nil {
		selector = lhq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if lhq.unique != nil && *lhq.unique {
		selector.Distinct()
	}
	for _, p := range lhq.predicates {
		p(selector)
	}
	for _, p := range lhq.order {
		p(selector)
	}
	if offset := lhq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lhq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LoginHistoryGroupBy is the group-by builder for LoginHistory entities.
type LoginHistoryGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lhgb *LoginHistoryGroupBy) Aggregate(fns ...AggregateFunc) *LoginHistoryGroupBy {
	lhgb.fns = append(lhgb.fns, fns...)
	return lhgb
}

// Scan applies the group-by query and scans the result into the given value.
func (lhgb *LoginHistoryGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := lhgb.path(ctx)
	if err != nil {
		return err
	}
	lhgb.sql = query
	return lhgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lhgb *LoginHistoryGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := lhgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (lhgb *LoginHistoryGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(lhgb.fields) > 1 {
		return nil, errors.New("ent: LoginHistoryGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := lhgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lhgb *LoginHistoryGroupBy) StringsX(ctx context.Context) []string {
	v, err := lhgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lhgb *LoginHistoryGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lhgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{loginhistory.Label}
	default:
		err = fmt.Errorf("ent: LoginHistoryGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lhgb *LoginHistoryGroupBy) StringX(ctx context.Context) string {
	v, err := lhgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (lhgb *LoginHistoryGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(lhgb.fields) > 1 {
		return nil, errors.New("ent: LoginHistoryGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := lhgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lhgb *LoginHistoryGroupBy) IntsX(ctx context.Context) []int {
	v, err := lhgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lhgb *LoginHistoryGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lhgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{loginhistory.Label}
	default:
		err = fmt.Errorf("ent: LoginHistoryGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lhgb *LoginHistoryGroupBy) IntX(ctx context.Context) int {
	v, err := lhgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (lhgb *LoginHistoryGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(lhgb.fields) > 1 {
		return nil, errors.New("ent: LoginHistoryGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := lhgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lhgb *LoginHistoryGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := lhgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lhgb *LoginHistoryGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lhgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{loginhistory.Label}
	default:
		err = fmt.Errorf("ent: LoginHistoryGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lhgb *LoginHistoryGroupBy) Float64X(ctx context.Context) float64 {
	v, err := lhgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (lhgb *LoginHistoryGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(lhgb.fields) > 1 {
		return nil, errors.New("ent: LoginHistoryGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := lhgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lhgb *LoginHistoryGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := lhgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lhgb *LoginHistoryGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lhgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{loginhistory.Label}
	default:
		err = fmt.Errorf("ent: LoginHistoryGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lhgb *LoginHistoryGroupBy) BoolX(ctx context.Context) bool {
	v, err := lhgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lhgb *LoginHistoryGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range lhgb.fields {
		if !loginhistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := lhgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lhgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (lhgb *LoginHistoryGroupBy) sqlQuery() *sql.Selector {
	selector := lhgb.sql.Select()
	aggregation := make([]string, 0, len(lhgb.fns))
	for _, fn := range lhgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(lhgb.fields)+len(lhgb.fns))
		for _, f := range lhgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(lhgb.fields...)...)
}

// LoginHistorySelect is the builder for selecting fields of LoginHistory entities.
type LoginHistorySelect struct {
	*LoginHistoryQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (lhs *LoginHistorySelect) Scan(ctx context.Context, v interface{}) error {
	if err := lhs.prepareQuery(ctx); err != nil {
		return err
	}
	lhs.sql = lhs.LoginHistoryQuery.sqlQuery(ctx)
	return lhs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lhs *LoginHistorySelect) ScanX(ctx context.Context, v interface{}) {
	if err := lhs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (lhs *LoginHistorySelect) Strings(ctx context.Context) ([]string, error) {
	if len(lhs.fields) > 1 {
		return nil, errors.New("ent: LoginHistorySelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := lhs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lhs *LoginHistorySelect) StringsX(ctx context.Context) []string {
	v, err := lhs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (lhs *LoginHistorySelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lhs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{loginhistory.Label}
	default:
		err = fmt.Errorf("ent: LoginHistorySelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lhs *LoginHistorySelect) StringX(ctx context.Context) string {
	v, err := lhs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (lhs *LoginHistorySelect) Ints(ctx context.Context) ([]int, error) {
	if len(lhs.fields) > 1 {
		return nil, errors.New("ent: LoginHistorySelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := lhs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lhs *LoginHistorySelect) IntsX(ctx context.Context) []int {
	v, err := lhs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (lhs *LoginHistorySelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lhs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{loginhistory.Label}
	default:
		err = fmt.Errorf("ent: LoginHistorySelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lhs *LoginHistorySelect) IntX(ctx context.Context) int {
	v, err := lhs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (lhs *LoginHistorySelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(lhs.fields) > 1 {
		return nil, errors.New("ent: LoginHistorySelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := lhs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lhs *LoginHistorySelect) Float64sX(ctx context.Context) []float64 {
	v, err := lhs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (lhs *LoginHistorySelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lhs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{loginhistory.Label}
	default:
		err = fmt.Errorf("ent: LoginHistorySelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lhs *LoginHistorySelect) Float64X(ctx context.Context) float64 {
	v, err := lhs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (lhs *LoginHistorySelect) Bools(ctx context.Context) ([]bool, error) {
	if len(lhs.fields) > 1 {
		return nil, errors.New("ent: LoginHistorySelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := lhs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lhs *LoginHistorySelect) BoolsX(ctx context.Context) []bool {
	v, err := lhs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (lhs *LoginHistorySelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lhs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{loginhistory.Label}
	default:
		err = fmt.Errorf("ent: LoginHistorySelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lhs *LoginHistorySelect) BoolX(ctx context.Context) bool {
	v, err := lhs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lhs *LoginHistorySelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := lhs.sql.Query()
	if err := lhs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
