// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// LoginHistory is the predicate function for loginhistory builders.
type LoginHistory func(*sql.Selector)
